name := "Assignment_Testing"
version := "0.1"
scalaVersion := "2.13.3"
libraryDependencies += "org.scalatest" %% "scalatest" % "3.2.2" % "test"
libraryDependencies +="org.mockito" %% "mockito-scala" % "1.16.15" % "test"
